### ISSUE TITLE
Inventory attribute for Box

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [RemDelaporteMathurin/system_code#34]

**Comment by SamueleMeschini** [comment]
Trivial point worth mentioning: we should be carefull with inventory units. The term $(n - I_m)$ expects $[I_m]$ = atoms/m3 (I guess), while the tritium inventories are usually reported in kg. Maybe using atoms/m3 (or  atoms/cm3) for internal calculations and kg for post-processing/visualization?

**Comment by RemDelaporteMathurin** [comment]
100% agree with you.

The equations here differ a bit from what you use since we don't use RTM but mass flows (which is equivalent at the end of the day).

The only disadvantage of using concentrations is that users need to provide volumes for components
